### ISSUE TITLE
[query] Using REST for sending message with properties

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge-testing-utility#11]
When debugging a single module natively, how to send a message with a property attached?

For e.g we use the curl command `curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data": "hello world"}' http://localhost:53000/api/v1/messages` to send message. But with that we cannot attach any message property. How to attach properties to messages when using curl command?

**Comment by yalaas** [comment]
@kiranpradeep  you can add "properties" to the POST data. Here is an example: 

curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data":"{\"key\":\"val\"}", "properties":{"prop": "val"}}' http://localhost:53000/api/v1/messages
